config/routes.rb
Rails.application.routes.draw do
  get 'recipe_image/new'
  get 'recipe_image/delete'
  get 'recipes/:id/mail' => 'recipes#mail', :as => 'mail_recipe'
  get 'recipes/:id/spam' => 'recipes#spam', :as => 'spam_recipe'
  get 'recipes/success'
  get 'recipes/failed'
  get 'recipes/index'
  root 'welcome#index'
  get 'welcome/about'
  #login routes
  get 'sessions/psuedo_destroy'
  get 'sessions/destroy'
  get 'auth/:provider/callback', to: 'sessions#new'
  get '/sessions/login'
  post 'sessions/create'
  post '/sessions/attempt_login'
  # Resources
  resources :ratings
  resources :users
  resources :tags
  resources :tags_recipes
  resources :measurements
  resources :recipes
  resources :recipe_images
  resources :recipe_ratings
  # invalid routes
  get '*path' => redirect('/') unless Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tags_recipe.rb
class TagsRecipe < ApplicationRecord
	belongs_to :tag
	belongs_to :recipe
        validates_uniqueness_of :tag_id, :scope => :recipe_id
end

app/controllers/tags_recipes_controller.rb
class TagsRecipesController < ApplicationController
  before_action :set_tags_recipe, only: [:show, :edit, :update, :destroy]

  # GET /tags_recipes
  # GET /tags_recipes.json
  def index
    @tags_recipes = TagsRecipe.all
  end

  # GET /tags_recipes/1
  # GET /tags_recipes/1.json
  def show
  end

  # GET /tags_recipes/new
  def new
    @tags_recipe = TagsRecipe.new
  end

  # GET /tags_recipes/1/edit
  def edit
  end

  # POST /tags_recipes
  # POST /tags_recipes.json
  def create
    @tags_recipe = TagsRecipe.new(tags_recipe_params)

    respond_to do |format|
      if @tags_recipe.save
        format.html { redirect_to @tags_recipe, notice: 'Tags added.' }
        format.json { render :show, status: :created, location: @tags_recipe }
      else
        format.html { render :new }
        format.json { render json: @tags_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags_recipes/1
  # PATCH/PUT /tags_recipes/1.json
  def update
    respond_to do |format|
      if @tags_recipe.update(tags_recipe_params)
        format.html { redirect_to @tags_recipe, notice: 'Tags recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @tags_recipe }
      else
        format.html { render :edit }
        format.json { render json: @tags_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags_recipes/1
  # DELETE /tags_recipes/1.json
  def destroy
    if current_user && (current_user == @recipe.user) || is_admin
      @tags_recipe.destroy
      respond_to do |format|
        format.html { redirect_to :back, notice: 'Tag removed.' }
        format.json { head :no_content }
      end
    else
      redirect_to (root_path)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tags_recipe
      @tags_recipe = TagsRecipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tags_recipe_params
      params.require(:tags_recipe).permit(:tag_id, :recipe_id)
    end
end

app/helpers/tags_recipes_helper.rb
module TagsRecipesHelper
end

app/views/tags_recipes/_form.html.erb
<%= form_for(tags_recipe) do |f| %>
  <% if tags_recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tags_recipe.errors.count, "error") %> prohibited this tags_recipe from being saved:</h2>

      <ul>
      <% tags_recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipe_id %>
    
    <% if params[:recipe_id].present? %>
      <%= f.hidden_field :recipe_id, :value => params[:recipe_id] %>
      <%= Recipe.find(params[:recipe_id]).recipe_name %>
    <%else%>
      <%= f.collection_select :recipe_id, Recipe.where( :user_id => current_user.id ), :id, :recipe_name %>
    <%end%>
  </div>

  <div class="field form-group">
    <%= f.label :tag_id, {for: 'tags_recipe_tag_id'} %>
    <%= f.collection_select :tag_id, Tag.where( :approved => 1 ) , :id, :tag_name, {:class => 'form-control'} %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit',{class: 'btn btn-primary'}   %>
  </div>
<% end %>

app/views/tags_recipes/edit.html.erb
<h1>Editing Tags Recipe</h1>

<%= render 'form', tags_recipe: @tags_recipe %>

<%= link_to 'Show', @tags_recipe %> |
<%= link_to 'Back', tags_recipes_path %>

app/views/tags_recipes/index.html.erb
<p id="notice"><%= notice %></p>

<%if is_admin%>
<h1>Tags Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th>Recipe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags_recipes.each do |tags_recipe| %>
    <% if is_admin %>
      <tr>
        <td><%= tags_recipe.tag.tag_name %></td>
        <td><%= tags_recipe.recipe.recipe_name %></td>
        <td><%= link_to 'Show', tags_recipe %></td>
        <td><%= link_to 'Edit', edit_tags_recipe_path(tags_recipe) %></td>
        <td><%= link_to 'Destroy', tags_recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tags Recipe', new_tags_recipe_path %> |
<%end%>

<%= link_to 'Back to previous page', :back %>

app/views/tags_recipes/new.html.erb
<h1>New Tags Recipe</h1>

<div class="container">
  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <%= render 'form', tags_recipe: @tags_recipe %>
    </div>

  </div>

</div>


<%= link_to 'Back', :back %>

app/views/tags_recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @tags_recipe.tag.tag_name %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @tags_recipe.recipe.recipe_name %>
</p>

<%= link_to 'Add more tags', :back %> |
<%= link_to 'Back to Recipe page', recipe_path(@tags_recipe.recipe_id) %>