config/routes.rb
Rails.application.routes.draw do
  get 'recipe_image/new'
  get 'recipe_image/delete'
  get 'recipes/:id/mail' => 'recipes#mail', :as => 'mail_recipe'
  get 'recipes/:id/spam' => 'recipes#spam', :as => 'spam_recipe'
  get 'recipes/success'
  get 'recipes/failed'
  get 'recipes/index'
  root 'welcome#index'
  get 'welcome/about'
  #login routes
  get 'sessions/psuedo_destroy'
  get 'sessions/destroy'
  get 'auth/:provider/callback', to: 'sessions#new'
  get '/sessions/login'
  post 'sessions/create'
  post '/sessions/attempt_login'
  # Resources
  resources :ratings
  resources :users
  resources :tags
  resources :tags_recipes
  resources :measurements
  resources :recipes
  resources :recipe_images
  resources :recipe_ratings
  # invalid routes
  get '*path' => redirect('/') unless Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  #Impressionist
  is_impressionable :counter_cache => true, :unique => :request_hash
  #image uploading
  mount_uploader :image, ImageUploader
  # Associations
  belongs_to :user
  has_many :recipe_ratings, :dependent => :delete_all
  has_many :tags_recipes, :dependent => :delete_all
  has_many :tags, -> {uniq}, :through => :tags_recipes
  has_many :recipe_images
  # Validations
  validates_presence_of :user_id
  validates_presence_of :recipe_name
  validates_presence_of :instructions
  validates :complexity, :numericality => { :greater_than => 0, less_than_or_equal_to: 10 }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :mail, :spam]
  # impressionist :unique => [:session_hash]
  # impressionist actions: :show

  def mail  #mail_recipe_path
    UserNotifierMailer.emailrecipe(@recipe, current_user).deliver
    redirect_to @recipe, notice: 'Email sent.'
  end

  def spam  # spam_recipe_path
    #users = User.where( :newsletter => true)
    users = User.all
    users.each do | user |
      UserNotifierMailer.newsletter(@recipe, user).deliver
    end
    redirect_to recipes_path, notice: 'Email sent.'
  end

  # GET /recipes
  # GET /recipes.json
  def index
    #finding recipes by clicking tags
    if params[:tag]
      @tagged_id = TagsRecipe.where(tag_id: params[:tag])
      i = 0
      recipeid = []
      until i == @tagged_id.size
        recipeid[i] = @tagged_id[i].recipe_id
        i = i+1
      end
      @recipes = Recipe.where(id: recipeid)
      @tags_recipes = TagsRecipe.all
    else
      @recipes = Recipe.all
      @tags_recipes = TagsRecipe.all
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    impressionist(@recipe)
    @tags_recipes = TagsRecipe.all
    @recipe_images = @recipe.recipe_images #returns an array of images for the current recipe
    @tags_recipe = TagsRecipe.new
    @tag = Tag.all
    @recipe_rating = RecipeRating.all
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @tags_recipe = TagsRecipe.new
    @tag = Tag.all
    current_user
  end

  # GET /recipes/1/edit
  def edit
  #   implicit @recipe created because of link
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if current_user.recipes << @recipe
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:recipe_name, :instructions, :complexity, :image)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(recipe, html: {multipart: true}) do |f| %>
    <%= error_messages_for_recipes(f.object)%>

    <div class="form-group">
      <%= f.label 'Main Recipe Image' %>
      <%= f.file_field :image %>
      <small>
        This image will be the image that identifies your recipe. <br>
        You can add more images to this recipe via the edit page.
      </small>
    </div>

    <div class="field form-group">
      <%= f.label :recipe_name %>
      <%= f.text_field :recipe_name,{class: 'form-control'} %>
     </div>

    <div class="field form-group">
      <%= f.label :instructions %>
      <%= f.text_field :instructions,{class: 'form-control'} %>
    </div>

    <div class="field form-group">
      <%= f.label :complexity %>
      <%= f.number_field :complexity,{class: 'form-control'} %>
    </div>

    <div class="field form-group">
      <% if recipe.user == nil %>
        <%= f.submit 'Create', {class: 'btn btn-primary'} %>
      <% else %>
        <%= f.submit 'Save', {class: 'btn btn-primary'} %>
      <% end %>
    </div>

<% end %>

app/views/recipes/edit.html.erb
<div class="page-header">
  <h1>Editing Recipe</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <%= render 'form', recipe: @recipe %>
    </div>
  </div>
</div>


<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/failed.html.erb
<<<<<<< HEAD
<h1>Recipes#failed</h1>
<p>Find me in app/views/recipes/failed.html.erb</p>
=======
<p>Recipe creation failed for some reason...</p>
>>>>>>> features/recipes

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1>Recipes</h1>
</div>
<div class="container">

  <% outerLoop = (@recipes.length/4.0).ceil %>
  <% innerLoopCounter = 0 %>
  <% accessCounter = 0 %>
  <% outerLoop.times do %>
    <div class="row">

    <% until innerLoopCounter == 4 || @recipes[accessCounter].nil? do %>
      <div class="col-md-3">
        <div class="thumbnail">
          <%= link_to @recipes[accessCounter] do %>
            <% if !@recipes[accessCounter].image.blank? %>
                <%= image_tag @recipes[accessCounter].image_url(:fb_fill_200).to_s %>
            <% else %>
                <%= image_tag '/recipePlaceholder.jpg', style: 'height:50px; width:50px'%>
            <% end %>
          <% end %>
          <div class="caption">
            <h5><%= @recipes[accessCounter].recipe_name %></h5>
            <p>
              <!--Tags-->
              Tags:<% @found = 0 %>
              <% @tags_recipes.each do |tags_recipe| %>
                  <% if tags_recipe.recipe_id == @recipes[accessCounter].id %>
                      <% @found = 1 %>
                      <a href="/recipes?tag[]=<%= tags_recipe.tag.id %>"><%= tags_recipe.tag.tag_name %> </a>
                  <% end %>
              <% end %>
              <% if @found == 0 %>
                  <i> None </i>
              <% end %>
            </p>
            <p>
              <!--Buttons-->
              <% if current_user.present? %>
                <%= link_to 'Email', mail_recipe_path(@recipes[accessCounter]), :class => 'btn btn-default btn-xs' %>
              <% end %>
              <% if (current_user && @recipes[accessCounter].user_id == current_user.id )|| is_admin %>
                  <%= link_to 'Edit', edit_recipe_path(@recipes[accessCounter]), class: 'btn btn-warning btn-xs' %>
                  <%= link_to 'Destroy', @recipes[accessCounter], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
              <% end %>
              <% if is_admin %>
                  <%= link_to 'Newsletter', spam_recipe_path(@recipes[accessCounter]),class: 'btn btn-default btn-xs' %>
              <% end %>
            </p>
          </div>
        </div>
      </div>
      <% innerLoopCounter = innerLoopCounter + 1 %>
      <% accessCounter += 1 %>
    <% end %>
      <% innerLoopCounter = 0 %>

    </div>
  <% end %>
</div>

<!-- going to be removed?
<% if current_user || is_admin %>
  <%= link_to 'New Recipe', new_recipe_path, {class: 'btn btn-default'} %> ||
  <%= link_to 'Add New Tag to a Recipe', new_tags_recipe_path, {class: 'btn btn-default'}%>
<% end %>
-->

app/views/recipes/new.html.erb
<div class="page-header">
  <h1>Create New Recipe</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <%= render 'form', recipe: @recipe %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<% content_for :for_head do %>
    <meta property="fb:app_id" content="519903674872413">
    <meta property="og:title" content="<%= @recipe.recipe_name %> - MasterChef">
    <meta property="og:type" content="website">
    <meta property="og:image" content="<%= @recipe.image_url(:fb_small).to_s %>">
    <meta property="og:image:secure_url" content="<%= @recipe.image_url(:fb_small).to_s %>">
    <meta property="og:image:type" content="image/jpeg">
    <meta property="og:image:width" content="500">
    <meta property="og:image:height" content="500">
    <meta property="og:image" content="<%= @recipe.image_url(:fb_medium).to_s %>">
    <meta property="og:image:secure_url" content="<%= @recipe.image_url(:fb_medium).to_s %>">
    <meta property="og:image:type" content="image/jpeg">
    <meta property="og:image:width" content="500">
    <meta property="og:image:height" content="500">
    <meta property="og:image" content="<%= @recipe.image_url(:fb_large).to_s %>">
    <meta property="og:image:secure_url" content="<%= @recipe.image_url(:fb_large).to_s %>">
    <meta property="og:image:type" content="image/jpeg">
    <meta property="og:image:width" content="500">
    <meta property="og:image:height" content="500">
    <meta property="og:url" content="<%= request.original_url %>">
<% end %>
<% if notice %>
    <div class="container">
      <div class="alert alert-info">
        <strong id="notice"><%= notice %></strong>
      </div>
    </div>
<% end %>

<!--Twitter and Facebook JS intializers-->
<!--Facebook-->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=519903674872413";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!--Twitter-->
<script>window.twttr = (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0],
      t = window.twttr || {};
  if (d.getElementById(id)) return t;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);

  t._e = [];
  t.ready = function(f) {
    t._e.push(f);
  };
  return t;
}(document, "script", "twitter-wjs"));</script>
<!--End of initializers-->
<div class="container">
  <div class="row">
    <div class="col-md-offset-4 col-md-4">
      <!--Recipe's main image-->
      <% if !@recipe.image.blank? %>
          <div class="thumbnail">
            <%= image_tag @recipe.image_url(:medium).to_s %>
            <div class="caption">
                <!--Share buttons-->
              <div class="fb-like" data-href="<%= request.original_url %>" data-layout="box_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div><br>

              <a class="twitter-share-button"
                 href="https://twitter.com/share"
                 data-size="small"
                 data-text="Recipe: <%= @recipe.recipe_name %> @MasterChef.com"
                 data-url="<%= Bitly.client.shorten(request.original_url.to_s).short_url %>"
                 data-hashtags="MasterChef,Recipe">
                Tweet
              </a>
              <!--End of share buttons-->
            </div>
          </div>
      <% end %>
      </div>
    </div>
  </div>

  <!-- About the recipe-->
  <ul class="list-group">
    <li class="list-group-item"> <strong>Recipe:</strong> <%= @recipe.id %></li>
    <li class="list-group-item"> <strong>User:</strong> <%= link_to @recipe.user.user_name, @recipe.user %></li>
    <li class="list-group-item"> <strong>Recipe name:</strong> <%= @recipe.recipe_name %></li>
    <li class="list-group-item"> <strong>Instructions:</strong> <%= @recipe.instructions %></li>
    <li class="list-group-item"> <strong>Complexity:</strong> <%= @recipe.complexity %></li>
  </ul>
</div>



<div class="container">
  <% if @recipe_images.empty? %>
      <p> No images to display</p>
  <% end %>
  <!--Recipes other images-->
  <% @recipe_images.each do |image|%>
      <div class="thumbnail">
        <%= image_tag image.image_url(:medium).to_s %>
        <%= link_to 'Delete', image, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger'%>
      </div>
  <% end %>
</div>
<p>
  <strong>Tags:</strong>
    <% @tags_recipes.each do |tags_recipe| %>
      <% if tags_recipe.recipe_id == @recipe.id%>
          <a href="/recipes?tag[]=<%= tags_recipe.tag.id %>"><%= tags_recipe.tag.tag_name %></a>
          <% if current_user && (current_user == @recipe.user) || is_admin %>
            <%= link_to '[X]', tags_recipe, method: :delete, data: { confirm: 'Are you sure?' } %> |
          <% end %>
      <% end %>
    <% end %>
    <% if current_user && (current_user == @recipe.user) || is_admin %>
	<%= link_to 'Add Tags', new_tags_recipe_path(:recipe_id => @recipe.id) %>
    <% end %>
</p>


<% if current_user && (current_user == @recipe.user) %>
    <%= link_to 'Add New Image', new_recipe_image_path(:recipe_id => @recipe.id), {class: 'btn btn-primary'} %> |
<% end %>

<% if (current_user && @recipe.user.id == current_user.id )|| is_admin %>
    <%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<% end %>
<%= link_to 'Back', recipes_path %>
<% if current_user.present? %>
  | <%= link_to 'Email Recipe', mail_recipe_path(@recipe) %>
<% end %>
<br><br><br>

<p>
  <strong>Comments</strong>
  <table>
    <% @recipe_rating.each do |recipe_rating| %>
      <% if recipe_rating.recipe_id == @recipe.id %>
      <tr><td>
	<%= link_to recipe_rating.user.user_name, recipe_rating.user %>
        <% if recipe_rating.rating != nil %>'s rating: <%= recipe_rating.rating %><%end%>
        <% if (current_user && recipe_rating.user_id == current_user.id) || is_admin %>
      	<%= link_to 'Delete', recipe_rating, method: :delete, data: { confirm: 'Are you sure?' } %><% end %>
	<br>
	<%= recipe_rating.comment %>
        <br>
      </td></tr>
      <% end %>
    <% end %>
  </table>
</p>
<br>
<% if current_user %>
  <form class="new_recipe_rating" id="new_recipe_rating" action="/recipe_ratings" accept-charset="UTF-8" method="post"><%= token_tag %><input type="hidden" name="authenticity_token" value="HwTVPG6rAMJkCaLtx949QGw/Y8O/ZBort+PY38JS9wx6OesRd4zNG/ywnOkW9Mf75RSIWWDg7fnxS6ljXkWu2A==" />

  <input type="hidden" name="recipe_rating[user_id]" id="recipe_rating_user_id" value="<%= current_user.id %>" />
  <input type="hidden" name="recipe_rating[recipe_id]" id="recipe_rating_recipe_id" value="<%= @recipe.id %>"/>
  <textarea rows="4" cols="50" name="recipe_rating[comment]" id="recipe_rating_comment" ></textarea><br>
  <input type="submit" name="commit" value="Add Comment" />
  </form>
<% end %>

app/views/recipes/success.html.erb
<<<<<<< HEAD
<h1>Recipes#success</h1>
<p>Find me in app/views/recipes/success.html.erb</p>
=======
<h1> Recipe creation successful! </h1>

<p> This page should show formatted information based on the users recipe.</p>
<p> What they submitted in the form should be added to a new database item </p>
<p> which will be echoed here </p>
>>>>>>> features/recipes