config/routes.rb
Rails.application.routes.draw do
  get 'recipe_image/new'
  get 'recipe_image/delete'
  get 'recipes/:id/mail' => 'recipes#mail', :as => 'mail_recipe'
  get 'recipes/:id/spam' => 'recipes#spam', :as => 'spam_recipe'
  get 'recipes/success'
  get 'recipes/failed'
  get 'recipes/index'
  root 'welcome#index'
  get 'welcome/about'
  #login routes
  get 'sessions/psuedo_destroy'
  get 'sessions/destroy'
  get 'auth/:provider/callback', to: 'sessions#new'
  get '/sessions/login'
  post 'sessions/create'
  post '/sessions/attempt_login'
  # Resources
  resources :ratings
  resources :users
  resources :tags
  resources :tags_recipes
  resources :measurements
  resources :recipes
  resources :recipe_images
  resources :recipe_ratings
  # invalid routes
  get '*path' => redirect('/') unless Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/measurement.rb
class Measurement < ApplicationRecord
end

app/models/rating.rb
class Rating < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  #Impressionist
  is_impressionable :counter_cache => true, :unique => :request_hash
  #image uploading
  mount_uploader :image, ImageUploader
  # Associations
  belongs_to :user
  has_many :recipe_ratings, :dependent => :delete_all
  has_many :tags_recipes, :dependent => :delete_all
  has_many :tags, -> {uniq}, :through => :tags_recipes
  has_many :recipe_images
  # Validations
  validates_presence_of :user_id
  validates_presence_of :recipe_name
  validates_presence_of :instructions
  validates :complexity, :numericality => { :greater_than => 0, less_than_or_equal_to: 10 }
end

app/models/recipe_image.rb
class RecipeImage < ApplicationRecord
  # upload images
  mount_uploader :image, ImageUploader
  # validations
  validates_presence_of :image
  # associations
  belongs_to :recipe
end

app/models/recipe_rating.rb
class RecipeRating < ApplicationRecord
	belongs_to :user
	belongs_to :recipe
end

app/models/tag.rb
class Tag < ApplicationRecord
	validates :tag_name, presence: true, :uniqueness => {:case_sensitive => false}
	validates :approved, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }
	has_many :tags_recipes, :dependent => :delete_all
	has_many :recipes, -> {uniq}, :through => :tags_recipes
end

app/models/tags_recipe.rb
class TagsRecipe < ApplicationRecord
	belongs_to :tag
	belongs_to :recipe
        validates_uniqueness_of :tag_id, :scope => :recipe_id
end

app/models/user.rb
class User < ApplicationRecord
	before_save :encrypt_password
  after_save :clear_password
	#image uploading
	mount_uploader :image, ImageUploader
	# Associations
	has_many :recipes, dependent: :destroy
	has_many :recipe_ratings, :dependent => :delete_all
	# Validations
  validates :encrypted_password, presence: true, unless: ->(user){user.password.present?}
	validates :user_name, presence: true, uniqueness: true
	validates_format_of :email, :with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
	validates :email, uniqueness: true
  # Methods
  def self.exists_from_omniauth(auth)
    find_by(provider: auth['provider'], uid: auth['uid']).present?
  end

	def self.sign_in_from_omniauth(auth)
		find_by(provider: auth['provider'], uid: auth['uid'])
	end

  def self.create_new_from_omniauth(auth)
    new(
        provider: auth['provider'],
        uid: auth['uid'],
        first_name: auth['extra']['raw_info']['first_name'],
        last_name: auth['extra']['raw_info']['last_name'],
				email: auth['info']['email']
    )
  end
  
  def clear_password
    self.password = nil
  end

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
    # For some reason after_save call back doesnt work, so I'm clearing password here
    clear_password
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:user_id, :recipe_id, :rating, :comment)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:tag_name, :approved)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for_users(object)
    render(:partial => 'application/error_messages', :locals => {:object => object})
  end

  def error_messages_for_recipes(object)
    render(:partial => 'application/error_messages_recipes', :locals => {:object => object})
  end

end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/recipe_image_helper.rb
module RecipeImageHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tags_recipes_helper.rb
module TagsRecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ratings/_form.html.erb
<%= form_for(rating) do |f| %>
  <% if rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :recipe_id %>
    <%= f.number_field :recipe_id %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ratings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Recipe</th>
      <th>Rating</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.user_id %></td>
        <td><%= rating.recipe_id %></td>
        <td><%= rating.rating %></td>
        <td><%= rating.comment %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @rating.user_id %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @rating.recipe_id %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @rating.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @rating.comment %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>